config/routes.rb
Rails.application.routes.draw do
  resources :survey_results
  resources :recipes
  resources :meal_kits
  resources :lifestyles
  resources :users

  # post '/users/new', to: 'users#new'
  # post 'users/new', to: 'sessions#new', as: 'new_login'
  post '/survey_results/new/', to: 'survey_results#assign_lifestyle', as: 'results'
  get '/users/:id', to: 'users#show', as: 'homepage'
  # get "signup", to: "users#new", as: "signup"

  # get “/login”, to: “sessions#new” 
  # post “/login”, to: “sessions#create” 

  get 'users/recipes/index', to: 'recipes#index', as: 'recipes_path'

  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/new', to: "sessions#login", as: 'login'
  delete '/sessions/reset', to: 'sessions#logout', as: 'logout'

  post '/users/new', to: 'users#new'

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lifestyle.rb
class Lifestyle < ApplicationRecord
    has_many :survey_results
    has_many :users, through: :survey_results
    has_one :meal_kit
    has_many :recipes

    def athletic_recipes
        Recipe.all.select {|r| r.lifestyle_id == self.id}
    end

    def healthy_recipes
        Recipe.all.select {|r| r.lifestyle_id == self.id}
    end

    def foodie_recipes
        Recipe.all.select {|r| r.lifestyle_id == self.id}
    end

    def hungry_recipes
        Recipe.all.select {|r| r.lifestyle_id == self.id}
    end

end

app/models/meal_kit.rb
class MealKit < ApplicationRecord
    belongs_to :lifestyle
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :lifestyle

    def athletic_recipes
        Recipe.all.select {|r| r.lifestyle_id == 1}
        recipes.sample(3)
    end

    def healthy_recipes
        Recipe.all.select {|r| r.lifestyle_id == 2}
    end

    def foodie_recipes
        Recipe.all.select {|r| r.lifestyle_id == 3}
    end

    def hungry_recipes
        Recipe.all.select {|r| r.lifestyle_id == 4}
    end

end

app/models/survey_result.rb
class SurveyResult < ApplicationRecord
    belongs_to :user
    belongs_to :lifestyle
end

app/models/user.rb
class User < ApplicationRecord
    has_many :survey_results
    has_many :lifestyles, through: :survey_results
    belongs_to :lifestyle, optional: true

    has_secure_password

    validates :username, uniqueness: { case_sensitive: false }
    validates :email, uniqueness: { case_sensitive: false }
    validates_presence_of :username, :email, :password

    def current_mealkit
        MealKit.all.select {|r| r.lifestyle_id == self.lifestyles[-1].id}
    end 

    def current_recipe_list
        Recipe.all.select {|r| r.lifestyle_id == self.lifestyles[-1].id}.sample(3)
    end 

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :find_current_user

    def find_current_user
        @current_user = User.find_by(id: cookies[:user_id])
    end 

end

app/controllers/lifestyles_controller.rb
class LifestylesController < ApplicationController
    def show
        @lifestyle = Lifestyle.find(params[:id])
    end
end

app/controllers/meal_kits_controller.rb
class MealKitsController < ApplicationController

    def index

    end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.all
        @lifestyles = Lifestyle.all
    end
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def login
        user = User.find_by(username: params[:session][:username])
    
        if user && user.authenticate(params[:session][:password])
          cookies[:user_id] = user.id
          redirect_to user_path(user)
        else
          flash[:errors] = "Username or Password does not match" 
          redirect_to new_login_path
        end 
    end 

  def logout
      cookies.delete(:user_id)
      redirect_to '/users'
  end 


    def create
      session[:user_id] = params[:user.id]
      redirect_to '/survey_results/new'
    end 

    # def create
    #     # no strong params cause there is no mass assignment
    #     @user = User.find_by(username: params[:username])
    #     if @user && @user.authenticate(params[:password])
    #       redirect_to @user
    #     else
    #       redirect_to login_path
    #     end
    # end

end 

app/controllers/survey_results_controller.rb
class SurveyResultsController < ApplicationController
    def new
    end
    
    def survey_answers
        score = []
        score << params[:survey][:answer_1]
        score << params[:survey][:answer_2]
        score << params[:survey][:answer_3]
        score << params[:survey][:answer_4]
        score << params[:survey][:answer_5]
        score << params[:survey][:answer_6]
        score << params[:survey][:answer_7]
        
        ls_scores = {
            athletic: score.select {|w| w == "athletic"}.count, 
            healthy: score.select {|w| w == "healthy"}.count, 
            foodie: score.select {|w| w == "foodie"}.count, 
            hungry: score.select {|w| w == "hungry"}.count
        }
    end

    def assign_lifestyle
        ls_array = survey_answers.max_by{|k, v| v}
        number = (Lifestyle.find_by(category: ls_array[0].to_s)).id
        SurveyResult.create(user_id: @current_user.id, lifestyle_id: number)
        # @current_user.lifestyle_id = number
        # @current_user.save
        # @current_user.update(lifestyle_id: number)
        # byebug
        redirect_to user_path(@current_user)
    end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recipes = Recipe.all
  end

  def new
    @user = User.new
  end 

  def create 
    user = User.create(user_params)

    if user.valid? 
      cookies[:user_id] = user.id
      redirect_to new_survey_result_path
    else
      flash[:my_errors] = user.errors.full_messages
      redirect_to new_user_path
    end 
  end 
    
  private 
    
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lifestyles_helper.rb
module LifestylesHelper
end

app/helpers/meal_kits_helper.rb
module MealKitsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/survey_results_helper.rb
module SurveyResultsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tailor ME(nu)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="hero is-info is-small">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item is-active">
              <%=button_to "Home", users_path, method: :get %>
            </a>

            <a class="navbar-item">
            <% if @current_user%>
              <%=button_to "Logout", logout_path, method: :delete%>
            <% else %>
              <%=button_to "Log In", new_login_path, method: :get %>
            <% end %>
            </a>
            
            <a class="navbar-item">
              <% if @current_user %>
                  Welcome <%= @current_user.username %>
              <% else %>
                  <%=button_to "Sign Up", new_user_path%>
              <% end %>
            </a>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title-image">
        <%= image_tag "logo.png"%>
      </p>
      <p class="subtitle">
        Curated recipes, based on your lifestyle.
      </p>
    </div>
  </div>

  <div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
      <div class="container">
        <ul>
        <li>
            <% if @current_user %>
              <%=link_to "Lifestyle", user_path(@current_user), method: :get%>
            <% end %>
          </li>
          <li>
            <% if @current_user && @current_user.lifestyles != [] %>
              <%=link_to "Recipes", recipes_path, method: :get %>
            <% end %>
          </li>
          <li>
            <% if @current_user && @current_user.lifestyles != [] %>
              <%=link_to "Meal Kit", meal_kits_path, method: :get%>
            <% end %>
          </li>
          
        </ul>
      </div>
    </nav>
  </div>

</section>
  <br>
    <%= yield %>
  </body>
</html>

app/views/lifestyles/show.html.erb
<h1><%= @lifestyle.category %></h1>

<h3><%= @lifestyle.description %></h3>

<%= button_to "View Your Curated Recipes", recipes_path, method: :get %>

app/views/meal_kits/index.html.erb
<% @current_user.current_mealkit.each do |r| %>
    <center>
        <ul>
            <section class="hero">
                <div class="hero-body">
                    <div class="container">
                        <h1 class="title">
                            <li><b><%=link_to r.provider, r.url, target: "_blank" %></b></li>
                        </h1>
                        <h2 class="subtitle">
                            <li><%= r.description %></li>     
                            <li>$<%= r.price.to_f %> per serving</li> </h2>
                            <br>    
                            <li><img src="<%= r.image %>" alt="<%= r.provider %>"%></li>
                            <br>
                            <br>
                        
                    </div>
                </div>
            </section>
        </ul>
    </center>
<% end %>
      

app/views/recipes/index.html.erb
<center>
<% @current_user.current_recipe_list.each do |r| %>
<ul>
    <li><b><%= r.title %></b></li>
    <li>Ready in <%= r.ready_in_minutes %> minutes</li>     
    <li><%= link_to "Full Recipe", r.source_url, target: "_blank" %></li> 
    <br>    
    <li><img src="<%= r.image %>" alt="<%= r.title %>"%></li>
    <br>
    <br>
    <li> <%= sanitize r.summary %></li>
    <br>
    <br>
</ul>
<% end %>

<div class="control">
  <button class="button is-success is-rounded"><%= button_to "More Recipes", recipes_path, :method => :get %></button>
</div> 

</center>

app/views/survey_results/new.html.erb
<section class="hero">
<%= form_for :survey do |f| %>
    <p class="title">What do you like to do in your free time?</p>
        <h2 class="subtitle"> <%= f.radio_button :answer_1, 'athletic'%> 
        <%= label_tag 'Workout' %> 
    <br>
        <%= f.radio_button :answer_1, 'healthy' %>
        <%= label_tag 'Grab a smoothie, duh' %>
    <br>
        <%= f.radio_button :answer_1, 'foodie' %>
        <%= label_tag 'Go to the trendiest restaurant' %>
    <br>
        <%= f.radio_button :answer_1, 'hungry' %>
        <%= label_tag 'Lounge at home' %></h2>
    <br>
    <p class="title">If you had a chance to travel anywhere in the world, where would you go?</p>
        <h2 class="subtitle"><%= f.radio_button :answer_2, 'athletic' %> 
        <%= label_tag 'Marathoning in Berlin' %>
    <br>
        <%= f.radio_button :answer_2, 'healthy' %>
        <%= label_tag 'Spa in Iceland' %>
    <br>
        <%= f.radio_button :answer_2, 'foodie' %>
        <%= label_tag 'Winery tour in Italy' %>
    <br>
        <%= f.radio_button :answer_2, 'hungry' %>
        <%= label_tag 'Vegas Debauchery Weekend' %></h2>
    <br>
      <p class="title">If you could sit down with a cultural figure, who would it be?</p>
        <h2 class="subtitle"><%= f.radio_button :answer_3, 'athletic' %> 
        <%= label_tag 'Michael Jordan' %>
    <br>
        <%= f.radio_button :answer_3, 'healthy' %>
        <%= label_tag 'Gweneth Paltrow' %>
    <br>
        <%= f.radio_button :answer_3, 'foodie' %>
        <%= label_tag 'Gordon Ramsey' %>
    <br>
        <%= f.radio_button :answer_3, 'hungry' %>
        <%= label_tag 'Kim Kardashian' %></h2>
    <br>
      <p class="title">Pick your favorite cuisine:</p>
        <h2 class="subtitle"><%= f.radio_button :answer_4, 'athletic' %> 
        <%= label_tag 'Greek' %>
    <br>
        <%= f.radio_button :answer_4, 'healthy' %>
        <%= label_tag 'Mediterranean' %>
    <br>
        <%= f.radio_button :answer_4, 'foodie' %>
        <%= label_tag 'French' %>
    <br>
        <%= f.radio_button :answer_4, 'hungry' %>
        <%= label_tag 'American' %></h2>
    <br>
      <p class="title">How adventurous are you?</p>
        <h2 class="subtitle"><%= f.radio_button :answer_5, 'athletic' %> 
        <%= label_tag 'VERY' %>
    <br>
        <%= f.radio_button :answer_5, 'healthy' %>
        <%= label_tag 'Sometimes...' %>
    <br>
        <%= f.radio_button :answer_5, 'foodie' %>
        <%= label_tag 'Not at all' %>
    <br>
        <%= f.radio_button :answer_5, 'hungry' %>
        <%= label_tag "What's does that even mean?" %></h2>
    <br>
      <p class="title">If you were stranded on a deserted island, what would you bring?</p>
        <h2 class="subtitle"><%= f.radio_button :answer_6, 'athletic' %> 
        <%= label_tag 'Pair of running shoes' %>
    <br>
        <%= f.radio_button :answer_6, 'healthy' %>
        <%= label_tag 'Smoothie and sunscreen' %>
    <br>
        <%= f.radio_button :answer_6, 'foodie' %>
        <%= label_tag 'Best bottle of wine' %>
    <br>
        <%= f.radio_button :answer_6, 'hungry' %>
        <%= label_tag 'Uh, a sandwich' %></h2>
    <br>
      <p class="title">What was the last genre of book you read?</p>
        <h2 class="subtitle"><%= f.radio_button :answer_7, 'athletic' %> 
        <%= label_tag 'Outdoor or Sports' %>
    <br>
        <%= f.radio_button :answer_7, 'healthy' %>
        <%= label_tag 'Nutrition' %>
    <br>
        <%= f.radio_button :answer_7, 'foodie' %>
        <%= label_tag 'Food' %>
    <br>
        <%= f.radio_button :answer_7, 'hungry' %>
        <%= label_tag 'Fiction' %></h2>
    <br>
    <p class="submit-btn">
      <%= f.submit 'Submit'%></p>
    <br>
    <br>
<% end %>
</section>

app/views/users/index.html.erb
<center>


<%= image_tag "homepage_image.jpeg"%>
<br>
<br>
</center>

app/views/users/new.html.erb
<center>
<h1 class="title">Create Your Account</h1>

<% if flash[:my_errors] %>
<ul>
<% flash[:my_errors].each do |error| %>
      <li><b><%= error %></b></li>
      <br>
<% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
      <%= f.label :username  %> 
      <%= f.text_field :username  %>
<br>
      <%= f.label :email  %>
      <%= f.text_field :email  %>
<br>
      <%= f.label :password %>
      <%= f.password_field :password  %>
<br>
<br>
<div class="control">
  <button class="button is-success is-rounded"><%= f.submit class: "form-btn" %></button>
</div> 
<% end %>
</center>



  

app/views/users/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
<%= "Welcome #{@current_user.username}!" %>
<br>
<br>
</h1>

<h2 class="subtitle">

    <% if @current_user.lifestyles != [] %>
      <ul>
        <h3>Looks like you're a pretty <b><%= @current_user.lifestyles.last.category %></b> person.</h3>
        <br>
        <p>Click <%= link_to "here", 'recipes/index' %> to see your curated recipes, or <%= link_to "here", '/meal_kits' %> for a suggested meal kit!</p> 
        <br>
        <h3>Not feeling <%= @current_user.lifestyles.last.category%>? Click <%= link_to "here", '/survey_results/new'%> to retake your survey!</h3>
      </ul>
    <% else %>

        <p>It looks like you haven't taken a survey yet. Please take it <%= link_to " here!", new_survey_result_path %></p>

    <% end %>
      </h2>
    </div>
  </div>
</section>